# Generated by Django 4.1.5 on 2023-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=255)),
            ],
        ),
    ]
