# Generated by Django 4.1.5 on 2023-02-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_has_xss_flag_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='my_email@email.com', max_length=255),
        ),
    ]
